name: mobile
description: Flutter-клиент для Best Product (задачи, авторизация).
publish_to: none
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.4.0
  cookie_jar: ^4.0.8
  dio_cookie_manager: ^3.1.0
  path_provider: ^2.1.2
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.5
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.3
  image: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icon/app_icon.png
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: assets/icon/app_icon.png
  remove_alpha_ios: true
